root: true
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - "prettier/@typescript-eslint"
  - "prettier/react"
plugins:
  - "@typescript-eslint"
  - react

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
settings:
  react:
    version: detect
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  eqeqeq:
    - error
    - always
  comma-dangle:
    - error
    - only-multiline
  overrides:
    - files:
        - "**/*.tsx"
      rules:
        "react/prop-types": off
        "react/jsx-props-no-spreading": off
